%% BMxsessionsPlot
% Designed to be compatible with workspace generated by BMxsessions.m


%% Plot: Timeplots
figure('position',[213.6,149.6,724.6666,425.3334]);

clear c L
for L = 1:3
    subplot(2,3,L)
    plot(tmp.STIM.refwin,sAVG.DE.aMUA.pc.layers.data(:,:,L),'color','b')
    hold on
    plot(tmp.STIM.refwin,sAVG.BIN.aMUA.pc.layers.data(:,:,L),'color','r')
    %ylimit = max(abs(get(gcf,'ylim')));
    ylimit = 100;
    set(gca,'ylim',[-10 ylimit],'Box','off','TickDir','out')
    ylabel({'Percent change'...
    'from baseline'});
    xlabel('time (ms)');
    if L == 1
        title('Supragranular');
    elseif L == 2
            title('Granular');
        else 
            title('Infragranular');
    end
end

clear c L
for L = 1:3
    for c = 1:4
    subplot(2,3,L+3)
    plot(tmp.STIM.refwin,((smooth(sAVG.BIN.aMUA.pc.layers.data(c,:,L)))-(smooth(sAVG.DE.aMUA.pc.layers.data(c,:,L)))),'linewidth',.1);
    hold on
    %ylimit = max(abs(get(gcf,'ylim')));
    ylimit = 50;
    set(gca,'ylim',[-10 ylimit],'Box','off','TickDir','out')
    ylabel({'Percent change'...
    'from baseline'});
    xlabel('time (ms)');
    end
end

sgtitle({'V1 laminae contrast responses: monoptic (blue) vs dioptic (red) stimulation'},'Interpreter','none');

%% Bar Graphs: Conditions

rcontrast = round(tmp.STIM.levels,2,'significant');

figure('Position', [155,98,965,487]);

labels = {0, 22, 45, 90,[],0,22,45,90}; format bank;

clear L c
for L = 1:3
subplot(2,3,L)
bar([sAVG.BIN.aMUA.pc.coll_layers.data(:,2,L);NaN;sAVG.BIN.aMUA.pc.coll_layers.data(:,3,L)],1,'FaceColor',[0.8500, 0.3250, 0.0980],'EdgeColor','k','LineWidth',0.8);
hold on
bar([sAVG.DE.aMUA.pc.coll_layers.data(:,2,L);NaN;sAVG.DE.aMUA.pc.coll_layers.data(:,3,L)],0.6,'FaceColor',[0, 0.4470, 0.7410],'EdgeColor','k','LineWidth',0.8);
bar([sAVG.NDE.aMUA.pc.coll_layers.data(:,2,L);NaN;sAVG.NDE.aMUA.pc.coll_layers.data(:,3,L)],0.4,'FaceColor',[.2, 0.2, 0.2],'EdgeColor','k','LineWidth',0.8);
set(gca,'box','off');
ylim([-5 55]);
xticklabels(labels)
xlabel('% contrast')
ylabel('Relative aMUA response');
    if L == 1
        title('Supragranular');
        legend('BIN','DE','NDE','location','northeast');
    elseif L == 2
            title('Granular');
        else 
            title('Infragranular');
    end
hold off
end

clear L c
for L = 1:3
    x1 = sAVG.BIN.aMUA.pc.coll_layers.data(:,2,L) - sAVG.DE.aMUA.pc.coll_layers.data(:,2,L);
    x2 = sAVG.BIN.aMUA.pc.coll_layers.data(:,3,L) - sAVG.DE.aMUA.pc.coll_layers.data(:,3,L);
    x3 = sAVG.BIN.aMUA.pc.coll_layers.data(:,2,L) - sAVG.NDE.aMUA.pc.coll_layers.data(:,2,L);
    x4 = sAVG.BIN.aMUA.pc.coll_layers.data(:,3,L) - sAVG.NDE.aMUA.pc.coll_layers.data(:,3,L);
subplot(2,3,L+3)
bar([x1;NaN;x2],1,'FaceColor',[0.8500, 0.5250, 0.7980],'EdgeColor','k','LineWidth',0.8);
hold on
bar([x3;NaN;x4],0.6,'FaceColor',[0.2500, 0.250, 0.2980],'EdgeColor','k','LineWidth',0.8);
set(gca,'box','off');
ylim([-5 30]);
xticklabels(labels)
xlabel('% contrast')
ylabel('difference');
hold off
end

sgtitle({'Binocular responses are stronger than their monocular counterparts'},'Interpreter','none');

%% Bar Graphs: Models (Dioptic)

figure('Position', [155,98,747.333,487]);

clear L c
for L = 1:3
subplot(3,3,L)
bar([sAVG.DE.aMUA.pc.coll_layers.data(:,2,L);NaN;sAVG.DE.aMUA.pc.coll_layers.data(:,3,L)],0.8,'FaceColor',[0, 0.4470, 0.7410],'EdgeColor','k','LineWidth',0.8);
hold on
bar([sAVG.NDE.aMUA.pc.coll_layers.data(:,2,L);NaN;sAVG.NDE.aMUA.pc.coll_layers.data(:,3,L)],0.6,'FaceColor',[.2, 0.2, 0.2],'EdgeColor','k','LineWidth',0.8);
set(gca,'box','off');
ylim([-5 80]);
xticklabels(labels)
xlabel('contrast')
ylabel('aMUA response');
    if L == 1
        title('Supragranular');
        lgd = legend('DE','NDE','location','northwest');
        lgd.FontSize = 5;
    elseif L == 2
            title('Granular');
        else 
            title('Infragranular');
    end
hold off
end

clear L c
for L = 1:3
subplot(3,3,L+3)
bar([sAVG.BIN.aMUA.pc_LSM.coll_layers.data(:,2,L);NaN;sAVG.BIN.aMUA.pc_LSM.coll_layers.data(:,3,L)],0.8,'FaceColor',[1, 1, 1],'linestyle','--','EdgeColor','k','LineWidth',0.8);
hold on
bar([sAVG.BIN.aMUA.pc.coll_layers.data(:,2,L);NaN;sAVG.BIN.aMUA.pc.coll_layers.data(:,3,L)],0.6,'FaceColor',[0.8500, 0.3250, 0.0980],'EdgeColor','k','LineWidth',0.8);
bar([sAVG.BIN.aMUA.pc_QSM.coll_layers.data(:,2,L);NaN;sAVG.BIN.aMUA.pc_QSM.coll_layers.data(:,3,L)],0.4,'FaceAlpha',[.05],'linestyle',':','EdgeColor','k','LineWidth',1);
set(gca,'box','off');
ylim([-5 80]);
xticklabels(labels)
xlabel('contrast')
ylabel('aMUA response');
hold off
    if L == 1
        lgd = legend('LSM','BIN','QSM','location','northwest');
        lgd.FontSize = 5;
    end
end

clear L
for L = 1:3
subplot(3,3,L+6)
bar([sAVG.BIN.aMUA.pc_LSM.coll_layers.data(:,2,L)-sAVG.BIN.aMUA.pc.coll_layers.data(:,2,L);NaN;sAVG.BIN.aMUA.pc_LSM.coll_layers.data(:,3,L)-sAVG.BIN.aMUA.pc.coll_layers.data(:,3,L)],0.8,'grouped','FaceColor',[1, 1, 1],'EdgeColor','k','LineWidth',0.8,'linestyle','--');
hold on
bar([sAVG.BIN.aMUA.pc_QSM.coll_layers.data(:,2,L)-sAVG.BIN.aMUA.pc.coll_layers.data(:,2,L);NaN;sAVG.BIN.aMUA.pc_QSM.coll_layers.data(:,3,L)-sAVG.BIN.aMUA.pc.coll_layers.data(:,3,L)],0.8,'grouped','FaceColor',[1, 1, 1],'EdgeColor','k','LineWidth',1,'linestyle',':');
set(gca,'box','off');
ylim([-15 30]);
xticklabels(labels);
xlabel('contrast')
ylabel('difference from model');
    if L == 1
        lgd = legend('LSM-BIN','QSM-BIN','location','northwest');
        lgd.FontSize = 5;
    end
hold off
end

sgtitle({'Linear summation generally overpredicts binocular responses'},'Interpreter','none');

%% Tightplot 
figure('position',[185,41.664,645.33,599.3333333333333]);

[ha, pos] = tight_subplot(2,3,[0.005 .03],[.10 .2],[.05 .05]); %channels, columns, [spacing], [bottom and top margin], [left and right margin]
clear c
for c = 1:3
    
    axes(ha(c)); % ha is a variable that gets the axis of each subplot
    plot(flipud(squeeze(sAVG.DE.aMUA.pc.coll.align(c+1,2,:))),1:36,'b','linewidth',.5);
    hold on
    %plot(flipud(squeeze(sAVG.BIN.aMUA.pc.coll.data(c+1,2,:))),tmp.STIM.channels,'.-r','linewidth',0.5);
    %hline(STIM.channels(end)-STIM.laminae.gran(end),'-.')
    xlim([-10 100])
    yticks('')
    yticklabels(fliplr(1:32))
    ylim([1 32])
    %yticklabels({flipud(1:length(STIM.channels))});
    grid on
    hold off
    xticklabels('');
    %xlabel('Percent change');
    
    if c == 1
        ylabel('Transient');
        title({tmp.STIM.levels(c+1),'contrast'});
    else 
        title({tmp.STIM.levels(c+1),'contrast'});
    end   
   
end

clear c
for c = 4:6
    
    axes(ha(c)); % ha is a variable that gets the axis of each subplot
    plot(flipud(squeeze(sAVG.DE.aMUA.pc.coll.align(c-2,3,:))),1:36,'b','linewidth',.5);
    hold on
    %plot(flipud(squeeze(sAVG.BIN.aMUA.pc.coll.data(c-2,3,:))),tmp.STIM.channels,'.-r','linewidth',0.5);
    %hline(STIM.channels(end)-STIM.laminae.gran(end),'-.')
    xlim([-10 100])
    yticks('')
    yticklabels(fliplr(1:32))
    ylim([1 32])
    %yticklabels({flipud(1:length(STIM.channels))});
    grid on
    hold off
    
    xlabel('Percent change'); 
    if c == 4
        ylabel('Sustained');
    else 
   
    end
end

sgtitle({'Aligned'},'interpreter','none')