function grating = readgDRFTGrating(filename, startRow, endRow)

%% output is structure array describing stimuli on each trial

% MAC, DEC 2014
% Made with help from MATLAB import data
% modified by Kacie for analyzing dot mapping code
% additional revisions Jan 2016 to add more features / corrections, make backwards compatable

%% Check Input
[~,BRdatafile,ext] = fileparts(filename);
if ~any(strcmp(ext,{'.gCONEINTEROCDRFTGrating_di','.gPOSDISPARITYDRFTGrating_di','.gDISPARITYDRFTGrating_di','.gBWFLICKERDRFTGrating_di','.gCOLORFLICKERDRFTGrating_di','.gTFSFDRFTGrating_di','.gRFSFDRFTGrating_di','.gRFORIDRFTGrating_di','.gCINTEROCDRFTGrating_di','.gCOSINTEROCDRFTGrating_di','.gRFSIZEDRFTGrating_di','.gCINTEROCORIDRFTGrating_di','.gMCOSINTEROCDRFTGrating_di','.gCPATCHDRFTGrating_di','.gCOLORFLICKERGrating_di','.gPMKDRFTGrating_di','.gCONEDRFTGrating_di'}));
    error('wrong filetype for this function')
end


%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
% For more information, see the TEXTSCAN documentation.
n = datenum(BRdatafile(1:6),'yymmdd');

clear fields formatSpec

if  n >= datenum('05/09/2016','mm/dd/yyyy') && n <= datenum('06/01/2016','mm/dd/yyyy')
    
    fields = {'trial'...
               'horzdva'...
               'vertdva' ...
               'xpos' ...
               'ypos'...	
               'tilt'...
               'sf'...
               'contrast' ...
               'fixedc' ...
               'diameter' ...
               'eye' ...
               'varyeye' ...
               'oridist' ...
               'gabor' ...
               'gabor_std' ...
               'header' ...
               'phase' ...
               'timestamp' ...
               'squarewave' ...
               'temporal_freq'}; 
 

    formatSpec = '%u\t%f\t%f\t%f\t%f\t%f\t%f\t%f\t%f\t%f\t%f\t%f\t%f\t%u\t%f\t%s\t%f\t%f\t%f\t%f\r\n';   

elseif n >= datenum('06/01/2016','mm/dd/yyyy') && n <= datenum('07/01/2016','mm/dd/yyyy')
    
   clear fields formatSpec 
    
    fields = {...
        'trial'...
        'horzdva'...
        'vertdva'...
        'xpos'...
        'ypos'...
        'otherxpos'...
        'otherypos'...
        'tilt'...
        'sf'...
        'contrast'...
        'fixedc'...
        'diameter'...
        'eye'...
        'varyeye'...
        'oridist'...
        'gabor'...
        'gabor_std'...
        'header'...
        'phase'...
        'timestamp'...
        'squarewave'...
        'temporal_freq'};

    
    formatSpec = '%u\t%f\t%f\t%f\t%f\t%f\t%f\t%f\t%f\t%f\t%f\t%f\t%f\t%f\t%s\t%u\t%f\t%s\t%f\t%f\t%f\t%f\r\n';
   
    
elseif n >= datenum('07/01/2016','mm/dd/yyyy') 
    
    fields = {...
        'trial'...
        'horzdva'...
        'vertdva'...
        'xpos'...
        'ypos'...
        'otherxpos'...
        'otherypos'...
        'tilt'...
        'sf'...
        'contrast'...
        'fixedc'...
        'diameter'...
        'eye'...
        'varyeye'...
        'oridist'...
        'gabor'...
        'gabor_std'...
        'header'...
        'phase'...
        'timestamp'...
        'squarewave'...
        'temporal_freq'...,
        'grating_disparity',...
        'fix_x'...
        'fix_y'...
        'path'};
    
    formatSpec = '%u\t%f\t%f\t%f\t%f\t%f\t%f\t%f\t%f\t%f\t%f\t%f\t%f\t%f\t%f\t%u\t%u\t%s\t%f\t%f\t%f\t%f\t%f\t%f\t%f\t%s\r\n';
    
else
    
    
    fields = {...
        'trial'...
        'horzdva'...
        'vertdva'...
        'xpos'...
        'ypos'...
        'tilt'...
        'sf'...
        'contrast'...
        'fixedc'...
        'diameter'...
        'eye'...
        'varyeye'...
        'oridist'...
        'gabor'...
        'gabor_std'...
        'header'...
        'phase'...
        'timestamp'...
        'squarewave'...
        'temporal_freq'...
        };
    formatSpec = '%u\t%f\t%f\t%f\t%f\t%f\t%f\t%f\t%f\t%f\t%f\t%f\t%f\t%u\t%u\t%s\t%f\t%f\t%f\t%f\r\n';
    
end


%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this code.

dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Allocate imported array to structure column variable names
if length(fields) ~= size(dataArray,2)
    error('bad formatSpec or structure fields for %s',filename)
end

% CORRECTIONS for File-Specific Issues
switch BRdatafile
    case '160115_E_rfori002'
        st = 41;
        en = length(dataArray{1});
    case '160128_I_rfori001'
        st = 296;
        en = length(dataArray{1});
    otherwise
        st = 1;
        en = length(dataArray{1});
end

for f = 1:length(fields)
    if isnumeric(dataArray{:, f})
        grating.(fields{f}) = double(dataArray{f}(st:en));
    else
        grating.(fields{f}) = dataArray{f}(st:en);
    end
end

ntrls          = max(grating.trial); % total trials
npres          = mode(histc(grating.trial,1:max(grating.trial))); % number of "gen" calls written / trial, may be diffrent from RECORD & what was actually shown
grating.pres   = repmat([1:npres]',ntrls,1);

grating.filename = filename;
grating.startRow = startRow;
grating.endRow = endRow;


%% CORRECTIONS FOR SPECIFIC FILES / FILE TYPES

grating.contrast   = double(round( grating.contrast   .* 1000) / 1000);
grating.fixedc     = double(round( grating.fixedc .* 1000) / 1000);

if strcmp(ext,'.gCOSINTEROCGrating_di')
    grating.oridist =  repmat(90,size(grating.oridist));
    
    n = datenum(BRdatafile(1:6),'yymmdd');
    
    if n <= datenum('151207','yymmdd');
        % Email from Kacie on Mon, Dec 7, 2015 at 5:49 PM: "The problem was that the text file was being written every time a stimulus was made for the left side of the screen.
        % This is because it was basing the saves off of  DOMEYE and not the GRATINGRECORD(CurrentTrialNumber).grating_eye.
        % I changed the code so it bases it off of grating_eye instead of DOMEYE."
        grating.eye =  repmat(3,size(gting.eye));
    end
end

% elseif
%     fields = {...
%         'trial'...
%         'horzdva'...
%         'vertdva'...
%         'xpos'...
%         'ypos'...
%         'otherxpos'...
%         'otherypos'...
%         'tilt'...
%         'sf'...
%         'contrast'...
%         'fixedc'...
%         'diameter'...
%         'eye'...
%         'varyeye'...
%         'oridist'...
%         'gabor'...
%         'gabor_std'...
%         'header'...
%         'phase'...
%         'timestamp'...
%         'squarewave'...
%         'temporal_freq'...,
%         'grating_disparity',...
%         'fix_x',...
%         'fix_y',...
%         'path'};
%     formatSpec = '%u\t%f\t%f\t%f\t%f\t%f\t%f\t%f\t%f\t%f\t%f\t%f\t%f\t%f\t%f\t%u\t%u\t%s\t%f\t%f\t%f\t%f\t%f\t%f\t%f\t%s\r\n';

