function [STIM,realtr] = sortStimandTimeData(grating,pEvC,pEvT,triggerto)


if ~isfield(grating,'pathw')
    if isfield(grating,'path')
        grating.pathw = grating.path;
    else
        grating.pathw = grating.contrast;
    end
end


clear spkTPs STIM
if any(strfind(grating.filename,'dotmapping'))
    stimfeatures = {...
        'trial'...
        'dot_x'...
        'dot_y'...
        'contrast'...
        'diameter'...
        };
elseif any(strfind(grating.filename,'coneinterocdrft'))
    stimfeatures = {'trial'...
        'tilt'...
        'sf'...
        'contrast'...
        'fixedc'...
        'diameter'...
        'eye'...
        'oridist'...
        'phase'...
        'temporal_freq',...
        'pathw'...
        'xpos'...
        'ypos'...
        'diameter'};
elseif (any(strfind(grating.filename,'colorflicker')))
    
    stimfeatures = {...
        'trial'...
        'tilt'...
        'sf'...
        'contrast'...
        'fixedc'...
        'diameter'...
        'eye'...
        'oridist'...
        'phase'...
        'temporal_freq',...
        'pathw'...
        'xpos'...
        'ypos'...
        'diameter'};
elseif any(strfind(grating.filename,'conedrft')) 
   
    stimfeatures = {...
        'trial'...
        'tilt'...
        'sf'...
        'contrast'...
        'fixedc'...
        'diameter'...
        'eye'...
        'oridist'...
        'phase'...
        'temporal_freq',...
        'path'...
        'xpos'...
        'ypos'...
        'diameter'};
    
elseif any(strfind(grating.filename,'color'))
        stimfeatures = {...
        'trial'...
        'tilt'...
        'sf'...
        'contrast'...
        'fixedc'...
        'diameter'...
        'eye'...
        'oridist'...
        'phase'...
        'pathw'...
         'xpos'...
        'ypos'...
        'diameter'};
    
elseif any(strfind(grating.filename,'disparity'))
    
    stimfeatures = {...
        'trial'...
        'tilt'...
        'sf'...
        'contrast'...
        'fixedc'...
        'diameter'...
        'eye'...
        'oridist'...
        'xpos'...
        'ypos'...
        'diameter'...
        'grating_disparity'...
        'pathw'...
        'temporal_freq'...
        };
    
    
elseif any(strfind(grating.filename,'drft')) || any(strfind(grating.filename,'bwflicker')) || any(strfind(grating.filename,'colorflicker')) & sum(grating.filename(1:6)<160801) == 6
    
    stimfeatures = {...
        'trial'...
        'tilt'...
        'sf'...
        'contrast'...
        'fixedc'...
        'diameter'...
        'eye'...
        'oridist'...
        'phase'...
        'temporal_freq',...
        'xpos'...
        'ypos'...
        'diameter'...
        };
elseif datenum(grating.filename(1:6),'yymmdd') < datenum('01/24/2016','mm/dd/yyyy') || isfield(grating,'phase')
    
    stimfeatures = {...
        'trial'...
        'tilt'...
        'sf'...
        'contrast'...
        'fixedc'...
        'diameter'...
        'eye'...
        'oridist'...
        'phase'...
        'xpos'...
        'ypos'...
        'diameter'...
        };
else
    
       stimfeatures = {...
        'trial'...
        'tilt'...
        'sf'...
        'contrast'...
        'fixedc'...
        'diameter'...
        'eye'...
        'oridist'...
        'xpos'...
        'ypos'...
        'diameter'...
        };
    
end

if isfield(grating,'fix_x')
    stimfeatures{end+1} = 'fix_x';
    stimfeatures{end+1} = 'fix_y';
end

if nargin == 3
    triggerto = 'stim';
end


obs = 0; realtr = [];
for t = 1: length(pEvC)
    
    codes  = pEvC{t};
    stim   = find(grating.trial == t);
    times  = pEvT{t};
 
    if isempty(find(grating.trial == t)) || any((strcmp(triggerto,'reward') & ~ismember(codes,96)))
        continue
    else
        
        realtr = [realtr t];
        if strcmp(triggerto,'stim')
            onsets  = times(find(codes == 23 | codes == 25 | codes == 27 | codes == 29 | codes == 31));
            offsets = times(find(codes == 24 | codes == 26 | codes == 28 | codes == 30 | codes == 32));
        elseif strcmp(triggerto,'reward')
            onsets = times(find(codes == 96));
        elseif strcmp(triggerto,'fix');
            onsets = times(find(codes == 35));
        end
        
        for p = 1:length(offsets)
            obs = obs + 1;
            
            STIM.onsets(obs,:)   = double(onsets(p));
            STIM.offsets(obs,:)  = double(offsets(p));
            STIM.trstart(obs,:)  = double(times(find(codes == 9,1,'first')));
            STIM.trend(obs,:)    = double(times(find(codes == 18,1,'first')));
            STIM.presnum(obs,:)  = p; 
            for f = 1:length(stimfeatures)
                STIM.(stimfeatures{f})(obs,:) = grating.(stimfeatures{f})(stim(p));
            end
            
            if length(grating.trial(stim)) == 2 || p == 1
                for f = 1:length(stimfeatures)
                    STIM.(stimfeatures{f})(obs,:) = grating.(stimfeatures{f})(stim(p));
                end
            elseif length(grating.trial(stim)) > 2 && p > 1 && any(strfind(grating.filename,'drft'))
                if strfind(grating.filename,'dotmapping')
                    for f = 1:length(stimfeatures)
                        STIM.(stimfeatures{f})(obs,:) = grating.(stimfeatures{f})(stim(p));
                    end
                else
                    for f = 1:length(stimfeatures)
                        STIM.(stimfeatures{f})(obs,:) = grating.(stimfeatures{f})(stim(p*2-1));
                    end
                end
            else
                for f = 1:length(stimfeatures)
                    STIM.(stimfeatures{f})(obs,:) = grating.(stimfeatures{f})(stim(p));
                end
                
            end   
        end
        
    end
end
